services:
  barracuda-navigation:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    container_name: barracuda-navigation
    network_mode: host
    restart: on-failure
    privileged: true
